title: LicenseGate
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://licensegate.io
color_scheme: licensegate
logo: "https://licensegate.io/images/logo.svg"

aux_links:
  Manage your licenses: https://app.licensegate.io

callouts:
  alternative:
    title: Alternative
    color: grey-lt
